# Generated by Django 5.2 on 2025-10-06 03:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
        ('libros', '0002_alter_libro_edicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPrestamo', models.DateField(default=datetime.date(2025, 10, 5))),
                ('fechaDevolucion', models.DateField()),
                ('estadoLibro', models.CharField(max_length=10)),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admins.bibliotecario')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admins.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.libro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fechaPrestamo'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDevolucion', models.DateField(default=datetime.date(2025, 10, 5))),
                ('estadoLibro', models.CharField(max_length=10)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
    ]
