# Generated by Django 5.2 on 2025-10-06 14:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        ('libros', '0002_alter_libro_edicion'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fechaDevolucion',
            field=models.DateField(default=datetime.date(2025, 10, 6)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='bibliotecario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='admins.bibliotecario'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateField(default=datetime.date(2025, 10, 6)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='admins.lector'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='libros.libro'),
        ),
    ]
