# Generated by Django 5.2 on 2025-10-06 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=100)),
                ('edicion', models.IntegerField(default=django.utils.timezone.now)),
                ('volumen', models.IntegerField(default=1)),
                ('paginas', models.IntegerField(default=100)),
                ('autores', models.ManyToManyField(related_name='libros', to='admins.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
