# Generated by Django 5.2 on 2025-10-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='edicion',
            field=models.IntegerField(default=2025),
        ),
    ]
